name: build

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - from: ubuntu:jammy
          release: antelope
          tag: 23.03.0
    steps:
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v2

    - name: Configure Buildkit
      uses: docker/setup-buildx-action@v2

    - name: Checkout project
      uses: actions/checkout@v3

    - name: Authenticate with Quay.io
      uses: docker/login-action@v2
      if: ${{ github.event_name == 'push' }}
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build image (ovn-central)
      uses: docker/build-push-action@v3
      with:
        target: ovn-central
        cache-from: type=gha,scope=${{ matrix.from }}-${{ matrix.release }}-${{ matrix.tag }}-central
        cache-to: type=gha,mode=max,scope=${{ matrix.from }}-${{ matrix.release }}-${{ matrix.tag }}-central
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: |-
          quay.io/vexxhost/ovn-central:${{ matrix.tag }}
        build-args: |-
          FROM=${{ matrix.from }}
          VERSION=${{ matrix.version }}

    - name: Build image (ovn-host)
      uses: docker/build-push-action@v3
      with:
        target: ovn-host
        cache-from: type=gha,scope=${{ matrix.from }}-${{ matrix.release }}-${{ matrix.tag }}-host
        cache-to: type=gha,mode=max,scope=${{ matrix.from }}-${{ matrix.release }}-${{ matrix.tag }}-host
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: |-
          quay.io/vexxhost/ovn-host:${{ matrix.tag }}
        build-args: |-
          FROM=${{ matrix.from }}
          VERSION=${{ matrix.version }}
